package com.dragon.alphaorder.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dragon.alphaorder.entity.Dishes;
import com.dragon.alphaorder.entity.Order;
import com.dragon.alphaorder.entity.User;

import com.dragon.alphaorder.greendao.DishesDao;
import com.dragon.alphaorder.greendao.OrderDao;
import com.dragon.alphaorder.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dishesDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig userDaoConfig;

    private final DishesDao dishesDao;
    private final OrderDao orderDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dishesDaoConfig = daoConfigMap.get(DishesDao.class).clone();
        dishesDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        dishesDao = new DishesDao(dishesDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Dishes.class, dishesDao);
        registerDao(Order.class, orderDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        dishesDaoConfig.clearIdentityScope();
        orderDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public DishesDao getDishesDao() {
        return dishesDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
